# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
    - 'main'
    paths-ignore:
    - README*
    - .github/workflows/build.yml
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: {} # none

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    permissions:
      contents: write  # for softprops/action-gh-release to create GitHub release
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install ccache libssl-dev u-boot-tools python3-mako debhelper fakeroot gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu make device-tree-compiler libncurses5-dev libelf-dev python3 python3-requests parted qemu-user-static debootstrap binfmt-support
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup env
        run: |
          echo "DT=$(date +'%Y-%m-%d_%H%M')" >> $GITHUB_ENV
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Generate Changelog
        run: |
          echo "# CI-Build for $BRANCH" > ${{ github.workspace }}-CHANGELOG.txt
          echo "last commits:" >> ${{ github.workspace }}-CHANGELOG.txt
          git log --pretty=format:"%h %ad %s %d by %an" --date=short >> ${{ github.workspace }}-CHANGELOG.txt

      - name: Print env
        run: |
          echo $BRANCH $DT

      - name: Setup cache
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ccache/
          key: ${{ runner.os }}-ccache-${{ github.ref_name }}
          restore-keys: |
            ${{ runner.os }}-ccache-${{ github.ref_name }}

      - name: Build for bananapi-r3
        run: |
          sudo apt install gcc-arm-linux-gnueabihf libc6-armhf-cross u-boot-tools bc make ccache gcc libc6-dev libncurses5-dev libssl-dev bison flex
          sudo apt install gcc-aarch64-linux-gnu u-boot-tools bc make gcc ccache libc6-dev libncurses5-dev libssl-dev bison flex curl
          curl -L -O https://github.com/spr-networks/BPI-Router-Linux-spr/releases/download/CI-BUILD-6.9-main-6.9.0-2024-09-19_1624/bpi-r3_6.9.0-main.tar.gz
          ./buildimg.sh bpi-r3 noble
      - name: Upload binaries to release
        if: endsWith(github.ref,'-main')
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          #draft: true
          #prerelease: true
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          body: ${{ github.sha }}-$BRANCH
          tag_name: "CI-BUILD-${{ env.BRANCH }}-${{ env.DT }}"
          target_commitish: ${{ github.sha }}
          files: |
            *.img.gz*
