# .github/workflows/main.yml
name: Main
on:
  push:
    branches:
      - 'main'
      - 'gdrive-test'
  workflow_dispatch:

jobs:
  gdrive-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install depencies
        run: |
          sudo apt update
          sudo apt install python3 parted qemu-user-static debootstrap binfmt-support

      - name: build R3 Debian Bookworm Image
        run: |
          ./buildimg.sh bpi-r3 bookworm
          mkdir bpi-r3
          mv *.img.gz bpi-r3

      - name: Upload to Google Drive
        uses: Jodebu/upload-to-drive@master
        with:
          target: bpi-r3
          credentials: ${{ secrets.CREDENTIALS }}
          folder: ${{ secrets.FOLDERID }}
