# .github/workflows/main.yml
name: Main
on:
  push:
    branches:
      - 'main'
      - 'gdrive-test'
  workflow_dispatch:

jobs:
  gdrive-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup env
        run: |
          echo "DT=$(date +'%Y-%m-%d_%H%M')" >> $GITHUB_ENV
          echo "DISTRO=bookworm" >> $GITHUB_ENV

      - name: Setup cache
        id: cache
        uses: actions/cache@v4
        with:
          path: "${{ env.DISTRO }}_*.tar.gz"
          key: ${{ runner.os }}-chroot
          restore-keys: ${{ runner.os }}-chroot

      - name: Install depencies
        run: |
          sudo apt update
          sudo apt install python3 parted qemu-user-static debootstrap binfmt-support

      - name: Build R64 Debian ${{ env.DISTRO }} Image
        run: |
          ./buildimg.sh bpi-r64 ${{ env.DISTRO }}

      #- name: Build R2Pro Debian Bookworm Image
      #  run: |
      #    ./buildimg.sh bpi-r2pro bookworm

      - name: Build R3 Debian ${{ env.DISTRO }} Image
        run: |
          ./buildimg.sh bpi-r3 ${{ env.DISTRO }}

      #- name: Upload to Google Drive
      #  uses: Jodebu/upload-to-drive@master
      #  with:
      #    target: bpi-r3
      #    credentials: ${{ secrets.CREDENTIALS }}
      #    folder: ${{ secrets.FOLDERID }}

      - name: Upload to gdrive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.CREDENTIALS }}
          filename: "*.img.gz"
          folderId: ${{ secrets.FOLDERID }}
          overwrite: "true" # optional boolean
